name: App CI

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/app-ci.yml'

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify credentials
        run: aws sts get-caller-identity

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login \
          --username AWS \
          --password-stdin 742820980479.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build image
        run: docker build -t aws-enterprise-capstone/app:latest ./app

      - name: Tag image
        run: |
          docker tag aws-enterprise-capstone/app:latest \
          742820980479.dkr.ecr.ap-south-1.amazonaws.com/aws-enterprise-capstone/app:latest

      - name: Push image
        run: |
          docker push \
          742820980479.dkr.ecr.ap-south-1.amazonaws.com/aws-enterprise-capstone/app:latest
