name: App CI

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/app-ci.yml'

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Verify credentials
        run: aws sts get-caller-identity

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login \
          --username AWS \
          --password-stdin 742820980479.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build image
        run: docker build -t aws-enterprise-capstone/app:latest ./app

      - name: Tag image
        run: |
          docker tag aws-enterprise-capstone/app:latest \
          742820980479.dkr.ecr.ap-south-1.amazonaws.com/aws-enterprise-capstone/app:latest

      - name: Push image
        run: |
          docker push \
          742820980479.dkr.ecr.ap-south-1.amazonaws.com/aws-enterprise-capstone/app:latest
